// Generated by sync-bunny-videos.mjs. No private API key is stored here.
window.BUNNY_MEDIA = [
  {
    "id": "f7715365-f3e1-4991-916a-e4e29f488f8d",
    "title": "19-20260501-194456.799356-slomo.mp4",
    "name": "19-20260501-194456.799356-slomo",
    "status": 2,
    "ready": false,
    "embed": "https://iframe.mediadelivery.net/embed/729308/f7715365-f3e1-4991-916a-e4e29f488f8d",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/f7715365-f3e1-4991-916a-e4e29f488f8d/thumbnail.jpg"
  },
  {
    "id": "d41b353b-ced9-4f95-b223-6e753825d362",
    "title": "17-20260501-194238.981372-slomo.mp4",
    "name": "17-20260501-194238.981372-slomo",
    "status": 2,
    "ready": false,
    "embed": "https://iframe.mediadelivery.net/embed/729308/d41b353b-ced9-4f95-b223-6e753825d362",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/d41b353b-ced9-4f95-b223-6e753825d362/thumbnail.jpg"
  },
  {
    "id": "7387985d-788f-4a15-8234-883d3ae2aaa9",
    "title": "16-20260501-194122.594943-slomo.mp4",
    "name": "16-20260501-194122.594943-slomo",
    "status": 2,
    "ready": false,
    "embed": "https://iframe.mediadelivery.net/embed/729308/7387985d-788f-4a15-8234-883d3ae2aaa9",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/7387985d-788f-4a15-8234-883d3ae2aaa9/thumbnail.jpg"
  },
  {
    "id": "3d69046a-184a-4a8b-bd9f-e49974e62ba7",
    "title": "15-20260501-194018.949888-slomo.mp4",
    "name": "15-20260501-194018.949888-slomo",
    "status": 2,
    "ready": false,
    "embed": "https://iframe.mediadelivery.net/embed/729308/3d69046a-184a-4a8b-bd9f-e49974e62ba7",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/3d69046a-184a-4a8b-bd9f-e49974e62ba7/thumbnail.jpg"
  },
  {
    "id": "e56f8d88-b8c2-472c-81da-a5296cc0325b",
    "title": "13-20260501-193547.710626-slomo.mp4",
    "name": "13-20260501-193547.710626-slomo",
    "status": 3,
    "ready": false,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e56f8d88-b8c2-472c-81da-a5296cc0325b",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e56f8d88-b8c2-472c-81da-a5296cc0325b/thumbnail.jpg"
  },
  {
    "id": "a0b22f0b-78ff-4dfc-b208-9cbf51906beb",
    "title": "14-20260501-193839.741693-slomo.mp4",
    "name": "14-20260501-193839.741693-slomo",
    "status": 3,
    "ready": false,
    "embed": "https://iframe.mediadelivery.net/embed/729308/a0b22f0b-78ff-4dfc-b208-9cbf51906beb",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/a0b22f0b-78ff-4dfc-b208-9cbf51906beb/thumbnail.jpg"
  },
  {
    "id": "ae2ab001-40bf-449a-adcc-0e7f582f6a3e",
    "title": "10-20260501-193118.136056-slomo.mp4",
    "name": "10-20260501-193118.136056-slomo",
    "status": 3,
    "ready": false,
    "embed": "https://iframe.mediadelivery.net/embed/729308/ae2ab001-40bf-449a-adcc-0e7f582f6a3e",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/ae2ab001-40bf-449a-adcc-0e7f582f6a3e/thumbnail.jpg"
  },
  {
    "id": "5b872604-5782-438e-862c-1e40fe7cb368",
    "title": "12-20260501-193411.358259-slomo.mp4",
    "name": "12-20260501-193411.358259-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/5b872604-5782-438e-862c-1e40fe7cb368",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/5b872604-5782-438e-862c-1e40fe7cb368/thumbnail.jpg"
  },
  {
    "id": "c97e3888-956c-47a9-965b-918818f5f91f",
    "title": "11-20260501-193255.898355-slomo.mp4",
    "name": "11-20260501-193255.898355-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/c97e3888-956c-47a9-965b-918818f5f91f",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/c97e3888-956c-47a9-965b-918818f5f91f/thumbnail.jpg"
  },
  {
    "id": "49b3f765-dc37-44a1-b2d1-941c127b9072",
    "title": "7-20260501-192733.763553-slomo.mp4",
    "name": "7-20260501-192733.763553-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/49b3f765-dc37-44a1-b2d1-941c127b9072",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/49b3f765-dc37-44a1-b2d1-941c127b9072/thumbnail.jpg"
  },
  {
    "id": "bc714227-19aa-495a-b9bd-8713696be186",
    "title": "9-20260501-193011.448608-slomo.mp4",
    "name": "9-20260501-193011.448608-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/bc714227-19aa-495a-b9bd-8713696be186",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/bc714227-19aa-495a-b9bd-8713696be186/thumbnail.jpg"
  },
  {
    "id": "977fc409-2ce1-4b71-800b-15db76e8fcde",
    "title": "8-20260501-192842.021094-slomo.mp4",
    "name": "8-20260501-192842.021094-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/977fc409-2ce1-4b71-800b-15db76e8fcde",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/977fc409-2ce1-4b71-800b-15db76e8fcde/thumbnail.jpg"
  },
  {
    "id": "4d49a928-d877-4ddf-9ebe-dd9d3390a11c",
    "title": "5-20260501-192453.451801-slomo.mp4",
    "name": "5-20260501-192453.451801-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/4d49a928-d877-4ddf-9ebe-dd9d3390a11c",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/4d49a928-d877-4ddf-9ebe-dd9d3390a11c/thumbnail.jpg"
  },
  {
    "id": "b588bfc7-1ec9-4ca8-9114-ee1e5756d398",
    "title": "6-20260501-192607.164888-slomo.mp4",
    "name": "6-20260501-192607.164888-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/b588bfc7-1ec9-4ca8-9114-ee1e5756d398",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/b588bfc7-1ec9-4ca8-9114-ee1e5756d398/thumbnail.jpg"
  },
  {
    "id": "2e7b9e74-5546-4adb-9dc8-808b54d01cba",
    "title": "3-20260501-192237.329372-slomo.mp4",
    "name": "3-20260501-192237.329372-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/2e7b9e74-5546-4adb-9dc8-808b54d01cba",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/2e7b9e74-5546-4adb-9dc8-808b54d01cba/thumbnail.jpg"
  },
  {
    "id": "ce4b7c57-291a-4c61-8750-d8a7314a6fea",
    "title": "4-20260501-192348.631738-slomo.mp4",
    "name": "4-20260501-192348.631738-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/ce4b7c57-291a-4c61-8750-d8a7314a6fea",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/ce4b7c57-291a-4c61-8750-d8a7314a6fea/thumbnail.jpg"
  },
  {
    "id": "78244e42-3867-4578-b24a-2140fc6a3d80",
    "title": "1-20260501-183353.132381-slomo.mp4",
    "name": "1-20260501-183353.132381-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/78244e42-3867-4578-b24a-2140fc6a3d80",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/78244e42-3867-4578-b24a-2140fc6a3d80/thumbnail.jpg"
  },
  {
    "id": "121facca-29e2-42fb-98c7-ae9c5e1a6a35",
    "title": "11-20260515-212317.482330-slomo.mp4",
    "name": "11-20260515-212317.482330-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/121facca-29e2-42fb-98c7-ae9c5e1a6a35",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/121facca-29e2-42fb-98c7-ae9c5e1a6a35/thumbnail.jpg"
  },
  {
    "id": "b68f9647-0360-467f-95b1-5b262b138206",
    "title": "13-20260515-212834.796988-slomo.mp4",
    "name": "13-20260515-212834.796988-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/b68f9647-0360-467f-95b1-5b262b138206",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/b68f9647-0360-467f-95b1-5b262b138206/thumbnail.jpg"
  },
  {
    "id": "b0d58ed9-10fe-4b5e-9c02-5cc21083feb5",
    "title": "12-20260515-212529.674142-slomo.mp4",
    "name": "12-20260515-212529.674142-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/b0d58ed9-10fe-4b5e-9c02-5cc21083feb5",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/b0d58ed9-10fe-4b5e-9c02-5cc21083feb5/thumbnail.jpg"
  },
  {
    "id": "b501cf5d-71b6-4072-bab2-efca2d4fd7fd",
    "title": "9-20260515-205024.021243-slomo.mp4",
    "name": "9-20260515-205024.021243-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/b501cf5d-71b6-4072-bab2-efca2d4fd7fd",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/b501cf5d-71b6-4072-bab2-efca2d4fd7fd/thumbnail.jpg"
  },
  {
    "id": "55aed91b-7785-498e-aeca-40aa4ca90082",
    "title": "10-20260515-205331.498693-slomo.mp4",
    "name": "10-20260515-205331.498693-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/55aed91b-7785-498e-aeca-40aa4ca90082",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/55aed91b-7785-498e-aeca-40aa4ca90082/thumbnail.jpg"
  },
  {
    "id": "997372fd-1598-4006-ab92-625cb474092e",
    "title": "9-20260515-205230.494856-slomo.mp4",
    "name": "9-20260515-205230.494856-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/997372fd-1598-4006-ab92-625cb474092e",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/997372fd-1598-4006-ab92-625cb474092e/thumbnail.jpg"
  },
  {
    "id": "cbd78244-4edd-4c4c-bb93-86f8e4abe56d",
    "title": "7-20260515-194028.153841-slomo.mp4",
    "name": "7-20260515-194028.153841-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/cbd78244-4edd-4c4c-bb93-86f8e4abe56d",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/cbd78244-4edd-4c4c-bb93-86f8e4abe56d/thumbnail.jpg"
  },
  {
    "id": "ad384fd6-6226-4273-b0f4-1cdd33297bdc",
    "title": "8-20260515-194148.813629-slomo.mp4",
    "name": "8-20260515-194148.813629-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/ad384fd6-6226-4273-b0f4-1cdd33297bdc",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/ad384fd6-6226-4273-b0f4-1cdd33297bdc/thumbnail.jpg"
  },
  {
    "id": "30db8eec-17ab-4e4e-9ecc-0eb28b1b9532",
    "title": "6-20260515-193906.219100-slomo.mp4",
    "name": "6-20260515-193906.219100-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/30db8eec-17ab-4e4e-9ecc-0eb28b1b9532",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/30db8eec-17ab-4e4e-9ecc-0eb28b1b9532/thumbnail.jpg"
  },
  {
    "id": "322076ea-e1bb-4d1c-803d-cd57b458b356",
    "title": "5-20260515-193800.040670-slomo.mp4",
    "name": "5-20260515-193800.040670-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/322076ea-e1bb-4d1c-803d-cd57b458b356",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/322076ea-e1bb-4d1c-803d-cd57b458b356/thumbnail.jpg"
  },
  {
    "id": "8776348d-2278-488a-a937-0c17f6a0dc91",
    "title": "4-20260515-193323.670618-slomo.mp4",
    "name": "4-20260515-193323.670618-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/8776348d-2278-488a-a937-0c17f6a0dc91",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/8776348d-2278-488a-a937-0c17f6a0dc91/thumbnail.jpg"
  },
  {
    "id": "9585b015-c226-47cd-a2ff-0872693d2bc9",
    "title": "49-20240608-231016.404665-slomo.mp4",
    "name": "49-20240608-231016.404665-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/9585b015-c226-47cd-a2ff-0872693d2bc9",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/9585b015-c226-47cd-a2ff-0872693d2bc9/thumbnail.jpg"
  },
  {
    "id": "e8d577ef-7370-4e8a-9376-27789a2a8bab",
    "title": "3-20260515-193136.897136-slomo.mp4",
    "name": "3-20260515-193136.897136-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e8d577ef-7370-4e8a-9376-27789a2a8bab",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e8d577ef-7370-4e8a-9376-27789a2a8bab/thumbnail.jpg"
  },
  {
    "id": "a8148404-c578-47c2-a4bc-088dd453df7a",
    "title": "1-20260515-192947.487984-slomo.mp4",
    "name": "1-20260515-192947.487984-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/a8148404-c578-47c2-a4bc-088dd453df7a",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/a8148404-c578-47c2-a4bc-088dd453df7a/thumbnail.jpg"
  },
  {
    "id": "f3d919dd-dd1a-4186-8243-d18d8edee6ca",
    "title": "53-20240608-232134.848541-slomo.mp4",
    "name": "53-20240608-232134.848541-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/f3d919dd-dd1a-4186-8243-d18d8edee6ca",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/f3d919dd-dd1a-4186-8243-d18d8edee6ca/thumbnail.jpg"
  },
  {
    "id": "6761c36e-943f-4c26-ac2f-f5317c4c79e5",
    "title": "52-20240608-231721.941460-slomo.mp4",
    "name": "52-20240608-231721.941460-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/6761c36e-943f-4c26-ac2f-f5317c4c79e5",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/6761c36e-943f-4c26-ac2f-f5317c4c79e5/thumbnail.jpg"
  },
  {
    "id": "49f511a2-2339-4c20-b78c-914dbb9bba67",
    "title": "50-20240608-231609.350818-slomo.mp4",
    "name": "50-20240608-231609.350818-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/49f511a2-2339-4c20-b78c-914dbb9bba67",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/49f511a2-2339-4c20-b78c-914dbb9bba67/thumbnail.jpg"
  },
  {
    "id": "83981777-cd6f-4dcb-a496-f6b189695130",
    "title": "48-20240608-230310.367377-slomo.mp4",
    "name": "48-20240608-230310.367377-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/83981777-cd6f-4dcb-a496-f6b189695130",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/83981777-cd6f-4dcb-a496-f6b189695130/thumbnail.jpg"
  },
  {
    "id": "e08c164c-6cbb-4f5b-a988-198d1259151d",
    "title": "47-20240608-230141.164459-slomo.mp4",
    "name": "47-20240608-230141.164459-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e08c164c-6cbb-4f5b-a988-198d1259151d",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e08c164c-6cbb-4f5b-a988-198d1259151d/thumbnail.jpg"
  },
  {
    "id": "e3645d89-faa1-4a39-a7c4-4e9e1bae8764",
    "title": "46-20240608-225839.837168-slomo.mp4",
    "name": "46-20240608-225839.837168-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e3645d89-faa1-4a39-a7c4-4e9e1bae8764",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e3645d89-faa1-4a39-a7c4-4e9e1bae8764/thumbnail.jpg"
  },
  {
    "id": "8a830e42-40c3-49b7-8a6c-fa03760ca9f1",
    "title": "45-20240608-225702.248212-slomo.mp4",
    "name": "45-20240608-225702.248212-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/8a830e42-40c3-49b7-8a6c-fa03760ca9f1",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/8a830e42-40c3-49b7-8a6c-fa03760ca9f1/thumbnail.jpg"
  },
  {
    "id": "e5433e2f-b47c-4aa0-a80e-9e58d6ce5a2d",
    "title": "44-20240608-225538.278268-slomo.mp4",
    "name": "44-20240608-225538.278268-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e5433e2f-b47c-4aa0-a80e-9e58d6ce5a2d",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e5433e2f-b47c-4aa0-a80e-9e58d6ce5a2d/thumbnail.jpg"
  },
  {
    "id": "1a1b9457-3b35-4193-8791-8db1a8f6afe8",
    "title": "40-20240608-222631.769132-slomo.mp4",
    "name": "40-20240608-222631.769132-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/1a1b9457-3b35-4193-8791-8db1a8f6afe8",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/1a1b9457-3b35-4193-8791-8db1a8f6afe8/thumbnail.jpg"
  },
  {
    "id": "a528c8f6-5e37-4c9b-91fb-4ef31c69f55b",
    "title": "43-20240608-225325.314086-slomo.mp4",
    "name": "43-20240608-225325.314086-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/a528c8f6-5e37-4c9b-91fb-4ef31c69f55b",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/a528c8f6-5e37-4c9b-91fb-4ef31c69f55b/thumbnail.jpg"
  },
  {
    "id": "eca9f52e-148a-452b-8ee3-b9da4392677a",
    "title": "42-20240608-224852.934185-slomo.mp4",
    "name": "42-20240608-224852.934185-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/eca9f52e-148a-452b-8ee3-b9da4392677a",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/eca9f52e-148a-452b-8ee3-b9da4392677a/thumbnail.jpg"
  },
  {
    "id": "e3ed99be-72a1-43e5-8413-7c75845d3c21",
    "title": "41-20240608-222751.103797-slomo.mp4",
    "name": "41-20240608-222751.103797-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e3ed99be-72a1-43e5-8413-7c75845d3c21",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e3ed99be-72a1-43e5-8413-7c75845d3c21/thumbnail.jpg"
  },
  {
    "id": "7d041179-927d-4ed9-924f-5c366ccff862",
    "title": "37-20240608-222336.844609-slomo.mp4",
    "name": "37-20240608-222336.844609-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/7d041179-927d-4ed9-924f-5c366ccff862",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/7d041179-927d-4ed9-924f-5c366ccff862/thumbnail.jpg"
  },
  {
    "id": "21cb409e-3618-4a9b-99a8-ad452aeaa454",
    "title": "34-20240608-222052.427534-slomo.mp4",
    "name": "34-20240608-222052.427534-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/21cb409e-3618-4a9b-99a8-ad452aeaa454",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/21cb409e-3618-4a9b-99a8-ad452aeaa454/thumbnail.jpg"
  },
  {
    "id": "59d63d26-7d8b-4882-b4f7-0ff54c282b75",
    "title": "36-20240608-222229.837635-slomo.mp4",
    "name": "36-20240608-222229.837635-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/59d63d26-7d8b-4882-b4f7-0ff54c282b75",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/59d63d26-7d8b-4882-b4f7-0ff54c282b75/thumbnail.jpg"
  },
  {
    "id": "4761c107-e3ae-4ebb-b831-5ecc0ad6691f",
    "title": "31-20240608-221755.150767-slomo.mp4",
    "name": "31-20240608-221755.150767-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/4761c107-e3ae-4ebb-b831-5ecc0ad6691f",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/4761c107-e3ae-4ebb-b831-5ecc0ad6691f/thumbnail.jpg"
  },
  {
    "id": "e86ebe72-371f-4279-884b-fb0e95768b3e",
    "title": "29-20240608-221451.967326-slomo.mp4",
    "name": "29-20240608-221451.967326-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e86ebe72-371f-4279-884b-fb0e95768b3e",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e86ebe72-371f-4279-884b-fb0e95768b3e/thumbnail.jpg"
  },
  {
    "id": "9012922f-77f0-46c4-919e-a9ef568c1173",
    "title": "30-20240608-221606.877745-slomo.mp4",
    "name": "30-20240608-221606.877745-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/9012922f-77f0-46c4-919e-a9ef568c1173",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/9012922f-77f0-46c4-919e-a9ef568c1173/thumbnail.jpg"
  },
  {
    "id": "046aac4b-da86-413b-815e-9f8aaeae12de",
    "title": "28-20240608-221324.133168-slomo.mp4",
    "name": "28-20240608-221324.133168-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/046aac4b-da86-413b-815e-9f8aaeae12de",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/046aac4b-da86-413b-815e-9f8aaeae12de/thumbnail.jpg"
  },
  {
    "id": "f1ecbb09-2372-408f-b244-cfe6ebc90d6d",
    "title": "27-20240608-221051.926831-slomo.mp4",
    "name": "27-20240608-221051.926831-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/f1ecbb09-2372-408f-b244-cfe6ebc90d6d",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/f1ecbb09-2372-408f-b244-cfe6ebc90d6d/thumbnail.jpg"
  },
  {
    "id": "0a9645a0-447f-41ba-aa4f-e6764939f1e6",
    "title": "26-20240608-220820.002917-slomo.mp4",
    "name": "26-20240608-220820.002917-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/0a9645a0-447f-41ba-aa4f-e6764939f1e6",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/0a9645a0-447f-41ba-aa4f-e6764939f1e6/thumbnail.jpg"
  },
  {
    "id": "53584854-4d8d-4c2b-b792-1c126e43a9bf",
    "title": "25-20240608-220611.545755-slomo.mp4",
    "name": "25-20240608-220611.545755-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/53584854-4d8d-4c2b-b792-1c126e43a9bf",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/53584854-4d8d-4c2b-b792-1c126e43a9bf/thumbnail.jpg"
  },
  {
    "id": "f8cc3ef4-d833-44d9-a1e4-d1a1b750abcf",
    "title": "24-20240608-220449.706012-slomo.mp4",
    "name": "24-20240608-220449.706012-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/f8cc3ef4-d833-44d9-a1e4-d1a1b750abcf",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/f8cc3ef4-d833-44d9-a1e4-d1a1b750abcf/thumbnail.jpg"
  },
  {
    "id": "2983c66c-f408-4f9c-bf2d-1b4eaac13ba6",
    "title": "22-20240608-220029.454718-slomo.mp4",
    "name": "22-20240608-220029.454718-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/2983c66c-f408-4f9c-bf2d-1b4eaac13ba6",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/2983c66c-f408-4f9c-bf2d-1b4eaac13ba6/thumbnail.jpg"
  },
  {
    "id": "b14c2c96-aa2d-4c84-aa93-ed08ef9abe5b",
    "title": "23-20240608-220208.006315-slomo.mp4",
    "name": "23-20240608-220208.006315-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/b14c2c96-aa2d-4c84-aa93-ed08ef9abe5b",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/b14c2c96-aa2d-4c84-aa93-ed08ef9abe5b/thumbnail.jpg"
  },
  {
    "id": "f66ca9a8-b690-49ed-854e-03a9bdd0a27f",
    "title": "20-20240608-215626.104231-slomo.mp4",
    "name": "20-20240608-215626.104231-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/f66ca9a8-b690-49ed-854e-03a9bdd0a27f",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/f66ca9a8-b690-49ed-854e-03a9bdd0a27f/thumbnail.jpg"
  },
  {
    "id": "db49ebc3-36f2-44c3-9d14-0f72b42b1ab9",
    "title": "21-20240608-215754.651528-slomo.mp4",
    "name": "21-20240608-215754.651528-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/db49ebc3-36f2-44c3-9d14-0f72b42b1ab9",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/db49ebc3-36f2-44c3-9d14-0f72b42b1ab9/thumbnail.jpg"
  },
  {
    "id": "e4d726cc-e41b-4a27-be25-ea8b656bf038",
    "title": "16-20240608-214728.478565-slomo.mp4",
    "name": "16-20240608-214728.478565-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e4d726cc-e41b-4a27-be25-ea8b656bf038",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e4d726cc-e41b-4a27-be25-ea8b656bf038/thumbnail.jpg"
  },
  {
    "id": "1f700dc8-c122-4af9-a8de-03464172a987",
    "title": "19-20240608-215202.404643-slomo.mp4",
    "name": "19-20240608-215202.404643-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/1f700dc8-c122-4af9-a8de-03464172a987",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/1f700dc8-c122-4af9-a8de-03464172a987/thumbnail.jpg"
  },
  {
    "id": "e18bf61f-37ef-46c2-b442-4d496a68cebf",
    "title": "18-20240608-214936.727093-slomo.mp4",
    "name": "18-20240608-214936.727093-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e18bf61f-37ef-46c2-b442-4d496a68cebf",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e18bf61f-37ef-46c2-b442-4d496a68cebf/thumbnail.jpg"
  },
  {
    "id": "d6d3ad14-9c90-4d42-b26c-d21b143f468d",
    "title": "13-20240608-214158.966799-slomo.mp4",
    "name": "13-20240608-214158.966799-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/d6d3ad14-9c90-4d42-b26c-d21b143f468d",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/d6d3ad14-9c90-4d42-b26c-d21b143f468d/thumbnail.jpg"
  },
  {
    "id": "86ffe37f-ac53-4ac4-8d1b-60eed4469b1a",
    "title": "15-20240608-214449.728011-slomo.mp4",
    "name": "15-20240608-214449.728011-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/86ffe37f-ac53-4ac4-8d1b-60eed4469b1a",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/86ffe37f-ac53-4ac4-8d1b-60eed4469b1a/thumbnail.jpg"
  },
  {
    "id": "5329c037-2daa-4914-b803-dd61fa24a4a9",
    "title": "14-20240608-214326.722718-slomo.mp4",
    "name": "14-20240608-214326.722718-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/5329c037-2daa-4914-b803-dd61fa24a4a9",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/5329c037-2daa-4914-b803-dd61fa24a4a9/thumbnail.jpg"
  },
  {
    "id": "eb679405-8234-4358-9f27-73e7535e3d82",
    "title": "11-20240608-214030.447889-slomo.mp4",
    "name": "11-20240608-214030.447889-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/eb679405-8234-4358-9f27-73e7535e3d82",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/eb679405-8234-4358-9f27-73e7535e3d82/thumbnail.jpg"
  },
  {
    "id": "dd09f497-10cf-43f6-833f-319cb94b2b04",
    "title": "10-20240608-213929.000115-slomo.mp4",
    "name": "10-20240608-213929.000115-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/dd09f497-10cf-43f6-833f-319cb94b2b04",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/dd09f497-10cf-43f6-833f-319cb94b2b04/thumbnail.jpg"
  },
  {
    "id": "b9d0dbe9-78e6-4c04-8df5-947c3ad7924c",
    "title": "9-20240608-213823.509632-slomo.mp4",
    "name": "9-20240608-213823.509632-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/b9d0dbe9-78e6-4c04-8df5-947c3ad7924c",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/b9d0dbe9-78e6-4c04-8df5-947c3ad7924c/thumbnail.jpg"
  },
  {
    "id": "d4691ab8-fdf1-46bf-ab83-3c98c2a315cc",
    "title": "6-20240608-213609.540256-slomo.mp4",
    "name": "6-20240608-213609.540256-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/d4691ab8-fdf1-46bf-ab83-3c98c2a315cc",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/d4691ab8-fdf1-46bf-ab83-3c98c2a315cc/thumbnail.jpg"
  },
  {
    "id": "e4c24120-2ad5-4e2f-8ab7-353d873229dc",
    "title": "4-20240608-183056.317836-video.mp4",
    "name": "4-20240608-183056.317836-video",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/e4c24120-2ad5-4e2f-8ab7-353d873229dc",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/e4c24120-2ad5-4e2f-8ab7-353d873229dc/thumbnail.jpg"
  },
  {
    "id": "909a23eb-49dd-40af-b089-8b5555bf94df",
    "title": "5-20240608-184106.736648-slomo.mp4",
    "name": "5-20240608-184106.736648-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/909a23eb-49dd-40af-b089-8b5555bf94df",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/909a23eb-49dd-40af-b089-8b5555bf94df/thumbnail.jpg"
  },
  {
    "id": "d07df809-7ce3-49be-beb2-51c5cac4a226",
    "title": "3-20240608-182400.387225-slomo.mp4",
    "name": "3-20240608-182400.387225-slomo",
    "status": 4,
    "ready": true,
    "embed": "https://iframe.mediadelivery.net/embed/729308/d07df809-7ce3-49be-beb2-51c5cac4a226",
    "poster": "https://vz-630224e7-6f3.b-cdn.net/d07df809-7ce3-49be-beb2-51c5cac4a226/thumbnail.jpg"
  }
];
