import { ArrowLeft, Camera as Instagram, ExternalLink, Mail, Phone } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getLead } from "@/lib/data";
import { Quality } from "@/components/lead-table";
import { LeadActions } from "@/components/lead-actions";
import type { Metadata } from "next";
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; const lead = await getLead(id); if (!lead) return { title: "Lead not found", openGraph: { images: [] }, twitter: { images: [] } }; const title = `${lead.businessName} | All Around Chi Town CRM`; const description = `${lead.category} lead in ${lead.city ?? "Chicagoland"}, scored ${lead.deterministicScore}/100.`; return { title, description, openGraph: { title, description, images: [] }, twitter: { title, description, images: [] } }; }
export default async function LeadDetail({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const lead = await getLead(id); if (!lead) notFound(); return <div className="page-shell"><Link href="/leads" className="mb-6 inline-flex items-center gap-2 text-xs text-zinc-500 hover:text-zinc-200"><ArrowLeft size={14} />Back to leads</Link><div className="grid gap-6 xl:grid-cols-[1fr_340px]"><div><section className="rounded-3xl border border-white/8 bg-[#111] p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><span className="grid size-14 place-items-center rounded-2xl bg-[#d5b36c]/10 text-xl font-semibold text-[#e2c276]">{lead.deterministicScore}</span><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{lead.businessName}</h1><Quality value={lead.quality} /></div><p className="mt-1 text-sm text-zinc-500">{lead.category} · {lead.city ?? "Location unavailable"}</p></div></div></div><div className="flex flex-wrap gap-2">{lead.website && <a href={lead.website} target="_blank" rel="noreferrer" className="quick-action"><ExternalLink size={14} />Website</a>}{lead.instagramUrl && <a href={lead.instagramUrl} target="_blank" rel="noreferrer" className="quick-action"><Instagram size={14} />Instagram</a>}{lead.email && <a href={`mailto:${lead.email}`} className="quick-action"><Mail size={14} />Email</a>}{lead.phone && <a href={`tel:${lead.phone}`} className="quick-action"><Phone size={14} />Call</a>}</div></div><div className="mt-8 rounded-2xl border border-[#d5b36c]/12 bg-[#d5b36c]/5 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[#a99161]">Why this lead fits</p><p className="mt-2 text-sm leading-6 text-zinc-300">{lead.fitReason ?? "Research has not been completed yet."}</p></div><dl className="mt-8 grid gap-x-8 gap-y-6 text-sm sm:grid-cols-2"><Info label="Email" value={lead.email} /><Info label="Phone" value={lead.phone} /><Info label="Website" value={lead.website} /><Info label="Source" value={lead.source.replaceAll("_", " ")} /><Info label="Rating" value={lead.rating ? `${lead.rating} (${lead.reviewCount ?? 0} reviews)` : null} /><Info label="Discovered" value={lead.createdAt.toLocaleDateString()} /></dl></section><section className="mt-6 rounded-3xl border border-white/8 bg-[#111] p-6"><h2 className="font-semibold">Activity history</h2><div className="mt-5 space-y-5">{lead.activities.map((activity) => <div key={activity.id} className="flex gap-4"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#d5b36c] shadow-[0_0_0_5px_rgba(213,179,108,.08)]" /><div><p className="text-sm font-medium">{activity.type.replaceAll("_", " ").toLowerCase()}</p><p className="mt-1 text-xs text-zinc-500">{activity.notes || "No additional notes"} · {activity.createdAt.toLocaleString()}</p></div></div>)}</div></section></div><LeadActions id={lead.id} status={lead.status} /></div></div>; }
function Info({ label, value }: { label: string; value?: string | null }) { return <div><dt className="text-xs text-zinc-600">{label}</dt><dd className="mt-1.5 break-words text-zinc-300">{value || "—"}</dd></div>; }
