"use client";
import { useState } from "react";
import { Search, X } from "lucide-react";
import { DEFAULT_CATEGORIES, DEFAULT_LOCATIONS } from "@/lib/constants";
export function FindLeads() {
  const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(formData: FormData) { setLoading(true); setMessage(""); try { const response = await fetch("/api/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(formData)) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Search failed"); setMessage(`Saved ${data.newLeadCount} new leads; ${data.duplicateCount} duplicates updated.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Search failed"); } finally { setLoading(false); } }
  return <><button onClick={() => setOpen(true)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#d5b36c] px-5 text-sm font-semibold text-[#171108]"><Search size={16} />Find leads</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#121212] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">Find local leads</h2><p className="mt-1 text-sm text-zinc-500">Search Google Places and save results to the CRM.</p></div><button onClick={() => setOpen(false)} aria-label="Close"><X className="text-zinc-500" size={20} /></button></div><form action={submit} className="mt-6 space-y-4"><label className="block text-sm text-zinc-400">Category<select name="category" className="field mt-2">{DEFAULT_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm text-zinc-400">Location<select name="location" className="field mt-2">{DEFAULT_LOCATIONS.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm text-zinc-400">Maximum results<input name="maxResults" type="number" min="1" max="20" defaultValue="10" className="field mt-2" /></label>{message && <p className="rounded-xl bg-white/5 p-3 text-sm text-zinc-300">{message}</p>}<button disabled={loading} className="h-11 w-full rounded-xl bg-[#d5b36c] text-sm font-semibold text-black disabled:opacity-50">{loading ? "Searching…" : "Run search"}</button></form></div></div>}</>;
}
