"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Camera as Instagram, Mail, Search } from "lucide-react";
type LeadRow = { id: string; businessName: string; deterministicScore: number; quality: string; category: string; city: string | null; email: string | null; instagramUrl: string | null; status: string; nextFollowUpAt: string | null; createdAt: string; source: string };
export function LeadTable({ leads, compact = false }: { leads: LeadRow[]; compact?: boolean }) {
  const [query, setQuery] = useState(""); const [quality, setQuality] = useState("ALL"); const filtered = useMemo(() => leads.filter((lead) => `${lead.businessName} ${lead.category} ${lead.city}`.toLowerCase().includes(query.toLowerCase()) && (quality === "ALL" || lead.quality === quality)).sort((a, b) => b.deterministicScore - a.deterministicScore), [leads, query, quality]);
  return <section className="overflow-hidden rounded-2xl border border-white/8 bg-[#111111]"><div className="flex flex-col gap-3 border-b border-white/8 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{compact ? "Priority leads" : "All leads"}</h2><p className="mt-1 text-xs text-zinc-500">{filtered.length} opportunities sorted by score</p></div>{!compact && <div className="flex gap-2"><label className="flex items-center gap-2 rounded-xl border border-white/8 bg-black/20 px-3"><Search size={14} className="text-zinc-600" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search leads" className="h-9 w-36 bg-transparent text-xs outline-none" /></label><select value={quality} onChange={(e) => setQuality(e.target.value)} className="rounded-xl border border-white/8 bg-[#171717] px-3 text-xs"><option value="ALL">All quality</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div>}</div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-[11px] uppercase tracking-wider text-zinc-600"><tr>{["Score", "Business", "Type", "Location", "Contact", "Quality", "Status", "Follow up"].map((item) => <th key={item} className="px-5 py-3 font-medium">{item}</th>)}</tr></thead><tbody>{filtered.slice(0, compact ? 5 : undefined).map((lead) => <tr key={lead.id} className="border-t border-white/6 text-zinc-400 transition hover:bg-white/[0.025]"><td className="px-5 py-4"><span className="inline-flex size-9 items-center justify-center rounded-full border border-[#d5b36c]/30 bg-[#d5b36c]/8 font-semibold text-[#e6c77f]">{lead.deterministicScore}</span></td><td className="px-5 py-4"><Link href={`/leads/${lead.id}`} className="font-medium text-white hover:text-[#e6c77f]">{lead.businessName}</Link>{lead.source === "WEBSITE_INQUIRY" && <span className="ml-2 rounded bg-sky-400/10 px-1.5 py-0.5 text-[9px] font-semibold text-sky-300">INQUIRY</span>}</td><td className="px-5 py-4">{lead.category}</td><td className="px-5 py-4">{lead.city ?? "—"}</td><td className="px-5 py-4"><span className="flex gap-2">{lead.email && <Mail size={14} className="text-emerald-400" />}{lead.instagramUrl && <Instagram size={14} className="text-fuchsia-400" />}{!lead.email && !lead.instagramUrl && "—"}</span></td><td className="px-5 py-4"><Quality value={lead.quality} /></td><td className="px-5 py-4">{lead.status.replaceAll("_", " ")}</td><td className="px-5 py-4">{lead.nextFollowUpAt ? new Date(lead.nextFollowUpAt).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "—"}</td></tr>)}{!filtered.length && <tr><td colSpan={8} className="px-5 py-12 text-center text-zinc-600">No leads match these filters.</td></tr>}</tbody></table></div></section>;
}
export function Quality({ value }: { value: string }) { const style = value === "HIGH" ? "bg-emerald-400/10 text-emerald-300" : value === "MEDIUM" ? "bg-amber-400/10 text-amber-300" : "bg-zinc-400/10 text-zinc-400"; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${style}`}>{value}</span>; }
